#!/bin/bash
apt update
apt upgrade -y
add-apt-repository multiverse
apt install software-properties-common
dpkg --add-architecture i386
apt update
apt install lib32gcc-s1 steamcmd
steamcmd
#login fansomid
#You can then download games by typing:
#force_install_dir <where you want to download the game files>
#app_update <game's appid> validate
# @sSteamCmdForcePlatformType windows
