#! /bin/bash

#username
#sudo adduser omid
#sudo usermod -aG sudo omid
#sudo sed -i 's/ALL=(ALL:ALL)/ALL=(ALL:ALL) NOPASSWD:ALL/g' /etc/sudoers
apt update
apt upgrade -y
#swap
echo Example: 4G
read -p "How much swapspace: " swap
fallocate -l $swap /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
cp /etc/fstab /etc/fstab.bak
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
sysctl vm.swappiness=10
sysctl vm.vfs_cache_pressure=50
echo sysctl vm.swappiness=10 >> /etc/sysctl.conflubuntu-desktop
echo vm.vfs_cache_pressure=50 >> /etc/sysctl.conf
#DE X2go
echo mate: mate-desktop-enviroment-extras
echo xfce: xubuntu-desktop
echo lxde: lubuntu-desktop
echo openbox: sudo apt-get install openbox obconf
read -p "Desktop Enviroment: " de
apt install $de -y
apt install x2goserver x2goserver-xsession -y
echo 'END'
reboot
